### ISSUE TITLE
Multiprocessing 

### ISSUE THREAD

**Issue by jasonfan1997** [seclark/RHT#15]
If it possible to run it using multiprocessing? Only one cpu will be used in current version.

**Comment by seclark** [comment]
It is certainly possible and the algorithm lends itself well to it. The way to do it is to feed the central fast_hough call with something like pool.apply_async. I haven't implemented this yet but feel free to open a pull request, it'd be great to get that going.

**Comment by jasonfan1997** [comment]
How about the interpret and viewer function ,it is not working now?May I ask what problem?

**Comment by seclark** [comment]
not currently supported, as it will tell you if you call it. I am of the opinion that there are too many use cases for the RHT to support imaging functions, but feel free to reach out if you have trouble interpreting your output. Also do check [the paper](http://adsabs.harvard.edu/abs/2014ApJ...789...82C) for a description of the algorithm if needed.
