### ISSUE TITLE
Documenting the second object from the output FITS file

### ISSUE THREAD

**Issue by issantos** [seclark/RHT#17]
I did not find any documentation regarding the way in which the X-Y-Theta power array is stored. What is the data format for the second object from the output FITS file?

For instance, in the function `RHT_tools.get_RHT_data`, what do `ipoints`, `jpoints` and `hthets` represent?

**Comment by seclark** [comment]
Hello! `ipoints` and `jpoints` are the indices in the original image coordinates, and `hthets` is the R(theta) spectrum for each pixel with nonzero RHT power. Please see [the example notebook](https://github.com/seclark/RHT/blob/master/RHT_example_workflow.ipynb) for a demo.

**Comment by seclark** [comment]
Closing this for now, since the new example notebook should explain the basics. But any improvements to that notebook or the documentation in general are welcome.
