### ISSUE TITLE
Header of the backprojection

### ISSUE THREAD

**Issue by issantos** [seclark/RHT#18]
Pass information from the header of the input file (e.g. positional information with `CRVAL1`, `CRPIX1`, `CDELT1`,...) to the header of the backprojection in the output FITS file.

**Comment by seclark** [comment]
Hello, thanks -- would be great to have you submit this as a PR!

**Comment by RRPJ** [comment]
Hi!

I, too, seek this function. I presume we read in data we seek from the original fits file, and then add it to the header at the section around line ~ 283, although I'm not precisely sure yet how. 

I'm pretty sure it's more extensive than that, since most functions use all the parameter as arguments, like getXYT and putXYT, and stuff like match_only. 

Is this not something worth expanding to?

I'll look into this a bit more.

Rutger

**Comment by RRPJ** [comment]
Hi!

So... I lack the expertise of actually doing this nicely with stuff like using the original input file path, but I did achieve the functionality I wanted. In putXYT() there are the following lines:

        # Other Header Values
        prihdr['NTHETA'] = ntheta

Below these lines I read in my own header and then pass anything I want. In my case, it was RA and DEC, including units and whatnot:

        my_header = fits.getheader("/some_folder/maybe_another_folder/your_file.fits")
        prihdr["CTYPE1"] = my_header["CTYPE1"]
        prihdr["CRVAL1"] = my_header["CRVAL1"]
        prihdr["CDELT1"] = my_header["CDELT1"]
        prihdr["CRPIX1"] = my_header["CRPIX1"]
        prihdr["CUNIT1"] = my_header["CUNIT1"]
        prihdr["CTYPE2"] = my_header["CTYPE2"]
        prihdr["CRVAL2"] = my_header["CRVAL2"]
        prihdr["CDELT2"] = my_header["CDELT2"]
        prihdr["CRPIX2"] = my_header["CRPIX2"]
        prihdr["CUNIT2"] = my_header["CUNIT2"]

Then running rht.py with your input file the same as the file where the header is loaded from of course, gives you the desired functionality.

It might be interesting to you @issantos 

Cheers!

Rutger

**Comment by seclark** [comment]
Hi both! Thank you for your work on this. @issantos do you think this settles the issue or is more functionality called for?

**Comment by RRPJ** [comment]
For the record, @issantos, this was also implemented by commit #19
