### ISSUE TITLE
Global parameter OUTPUT not used?

### ISSUE THREAD

**Issue by RRPJ** [seclark/RHT#21]
The global parameter OUTPUT, from which you can define an output directory, doesn't do anything. I'm decently sure it's not been implemented, but if it is, it does not work for me.

**Comment by seclark** [comment]
You are right, this is not implemented yet. An option would be appending it to the beginning of `xyt_filename` and changing OUTPUT to "" so that the default behavior is still the current directory. I can implement this; let me know if you have something else in mind.

**Comment by RRPJ** [comment]
I am not too sure if that will work. As I understand and checked, `xyt_filename` is the complete filename with directories (as in, the path). 

If we append OUTPUT to the beginning, which is /home/some_directory/maybe_another/, to `xyt_filename`, we get /home/some_directory/maybe_another/home/some_directory/input_directory/input_file.fits

I am not certain how we will get the input file name only, as that will be the solution - then we can append OUTPUT to the beginning. I'll investigate a bit.

**Comment by seclark** [comment]
Very right-- I was thinking of just adding this where the file is written, i.e. in the writeto call. Is it needed elsewhere?

**Comment by RRPJ** [comment]
You mean this line at the end of putXYT() right?
'thdulist.writeto(xyt_filename, output_verify='silentfix', overwrite=True, checksum=True)'

This is indeed where I saw this going aswell. However, how are we going to do this?
If we put 'OUTPUT/xyt_filename' where there is 'xyt_filename' now, we get the issue I described last post.

Or can we do some magic with the pathname itself, get rid of it somehow? I know there is a pathname variable in the script, for example.

**Comment by seclark** [comment]
Yes, how about just
`thdulist.writeto(OUTPUT+xyt_filename, output_verify='silentfix', overwrite=True, checksum=True)`

or am I missing something? I suppose it'd be nice to have something that checks that if OUTPUT is specified, it ends in a trailing "/".

**Comment by RRPJ** [comment]
Hi,

I might not have been clear. 

Say I set `OUTPUT` to `/dir1/dir2/Output`
`xyt_filename` is `/dir1/dir2/Input/file.fits`

Then writing it to `OUTPUT+xyt_filename` would result in it writing to:
`/dir1/dir2/Output/dir1/dir2/Input/file.fits`

The clue is that `xyt_filename` _is the complete path plus the filename_. Sorry if that wasn't clear earlier.

**Comment by seclark** [comment]
Ah I see, good call. Maybe this is best handled inside `xyt_name_factory`, setting `dirname` to an input path rather than the current directory?

**Comment by RRPJ** [comment]
I was thinking just now of adding an if statement in `xyt_name_factory`. 
If `OUTPUT` is not '.' (meaning the user set a different output directory than the current), then `xyt_filename` should be `OUTPUT/file.fits`, instead of what it is now. Let me see if I can make that a PR.

**Comment by RRPJ** [comment]
Fixed by #22
