### ISSUE TITLE
array input rather than filename

### ISSUE THREAD

**Issue by jslavin** [seclark/RHT#24]
Hi,

I was wondering if you had any inclination to add the capability of using an array as input to rht.main() rather than a filename. For me that'd be useful because I have an image that I want to crop before processing. I might also want to do some pre-processing to the data (e.g. a small bit of smoothing to reduce the noisiness). Of course I could write the data out to a fits file and then use that, but that would be a bit less convenient and would produce an unnecessary file.
I might do that myself, and of course would share it with you if you'd like.

Jon

**Comment by seclark** [comment]
Hi Jon,
I have no immediate plans to implement this feature, but I imagine you are not alone in wanting a convenient way to do this. You could just call `window_step` in your code directly, but it might be nice to write a wrapper around it. It'd be great if you want to implement this!

**Comment by seclark** [comment]
Looks great Jon, thanks.
